version: '3.9'

services:
  engine:
    build:
      context: .
      target: development
    ports:
      - '3000:3000'
    depends_on:
      - activemq
    env_file: .env
    environment:
      MQTT_HOST: activemq
      MQTT_PORT: 1883
    volumes:
      - ./src:/app/src
    command: ['/wait-for', 'activemq:1883', '--', 'npm', 'run', 'start:dev']
  activemq:
    image: rmohr/activemq
    ports:
      - '8161:8161'
      - '1883:1883'