name: Build and Deploy - Staging

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
env: 
  DOCKER_IMAGE: dmi/engine

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . \
        --file Dockerfile \
        --target production \
        --tag ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
    - name: Docker ECR
      uses: appleboy/docker-ecr-action@v0.0.3
      with:
        access_key: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
        secret_key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
        registry: 216821345641.dkr.ecr.us-east-2.amazonaws.com/diagnostic-modality-integration-engine
        region: us-east-2
    
